/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bcc9c8",
        "surface-container-low": "#eef5f7",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed": "#8cf3f3",
        "inverse-surface": "#2b3234",
        "secondary-container": "#fe9331",
        "on-secondary-fixed-variant": "#6f3900",
        "surface-container-high": "#e2e9ec",
        "on-tertiary-container": "#f3fffd",
        "background": "#f4fafd",
        "primary": "#006767",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb77f",
        "tertiary-fixed-dim": "#59dad1",
        "primary-fixed-dim": "#6fd7d6",
        "on-surface-variant": "#3d4949",
        "surface-variant": "#dde4e6",
        "on-primary-fixed-variant": "#004f4f",
        "on-secondary-fixed": "#2f1500",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002020",
        "on-secondary-container": "#673400",
        "inverse-primary": "#6fd7d6",
        "surface-container": "#e8eff1",
        "inverse-on-surface": "#ebf2f4",
        "on-primary": "#ffffff",
        "primary-container": "#008282",
        "secondary": "#914c00",
        "surface-bright": "#f4fafd",
        "tertiary": "#006762",
        "tertiary-fixed": "#79f6ed",
        "surface-tint": "#006a6a",
        "on-tertiary": "#ffffff",
        "on-background": "#161d1f",
        "on-tertiary-fixed-variant": "#00504c",
        "surface-container-highest": "#dde4e6",
        "secondary-fixed": "#ffdcc4",
        "on-primary-container": "#f3fffe",
        "surface-dim": "#d4dbdd",
        "on-surface": "#161d1f",
        "error": "#ba1a1a",
        "tertiary-container": "#00837c",
        "on-tertiary-fixed": "#00201e",
        "outline": "#6d7979",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        lg: "48px",
        gutter: "24px",
        md: "24px",
        xl: "80px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        sm: "12px",
        base: "8px",
      },
      fontFamily: {
        "label-lg": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "display-lg": ["Be Vietnam Pro"],
        "label-sm": ["Be Vietnam Pro"],
        "headline-md": ["Be Vietnam Pro"],
        "headline-lg": ["Be Vietnam Pro"],
        "headline-lg-mobile": ["Be Vietnam Pro"],
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
